name: my_planner_pro
description: "یک اپلیکیشن حرفه‌ای برای مدیریت فعالیت‌های روزانه."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1

  # Local Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2

  # Routing
  go_router: ^13.2.0

  # Models & Equality
  equatable: ^2.0.5

  # Date Formatting (نسخه سازگار با Flutter SDK جدید)
  intl: ^0.19.0
  shamsi_date: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  isar_generator: ^3.1.0+1


flutter:
  uses-material-design: true

