name: my_planner_pro
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0-417.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Added missing packages that were causing build errors.
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.1
  equatable: ^2.0.5

  isar: ^3.1.0+1
  path_provider: ^2.0.12
  get: ^4.6.5
  persian_datetime_picker: ^2.6.0
  shamsi_date: ^1.0.1
  flutter_localization: ^0.2.0
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  build_runner: ^2.3.3
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

